name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        os: [linux, windows, darwin]
        arch: [amd64, arm64]

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: "go.mod"

      - run: |
          GOOS=${{ matrix.os }} GOARCH=${{ matrix.arch }} go mod download
          GOOS=${{ matrix.os }} GOARCH=${{ matrix.arch }} go test -v -race ./...
          GOARCH=${{ matrix.arch }} GOOS=${{ matrix.os }} go build -v -o go-ws-proxy main.go

      - uses: actions/upload-artifact@v4
        with:
          name: go-ws-proxy-${{ matrix.os }}-${{ matrix.arch }}
          path: go-ws-proxy
